name: AntiVillagerLag
version: '${project.version}'
main: rebelmythik.antivillagerlag.AntiVillagerLag
api-version: 1.17

commands:
  avlreload:
    description: reloads the config
    permission: avl.reload
  avloptimize:
    description: will disable all the nearby villagers
    permission: avl.optimize

permissions:
  avl.disable:
    description: Allows disabling AVL for users or worlds
    default: false
  avl.reload:
    description: Allows user to reload the config
    default: op
  avl.restockcooldown.bypass:
    description: Allows the player to bypass the restock on renaming villagers
    default: false
  avl.renamecooldown.bypass:
    description: Allows the player to bypass the cooldown on renaming villagers
    default: false
  avl.blockcooldown.bypass:
    description: Allows the player to bypass the cooldown on renaming villagers
    default: false
  avl.message.nextrestock:
    description: Tells the player when the villager is restocking next
    default: true
  avl.optimize:
    description: Lets you disable villagers is a radius
    default: op
